[2025-05-22T06:36:05.626+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-22T06:36:05.639+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_producer scheduled__2025-05-21T16:00:00+00:00 [queued]>
[2025-05-22T06:36:05.650+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_minio_to_spark.kafka_producer scheduled__2025-05-21T16:00:00+00:00 [queued]>
[2025-05-22T06:36:05.651+0000] {taskinstance.py:2865} INFO - Starting attempt 9 of 11
[2025-05-22T06:36:05.658+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): kafka_producer> on 2025-05-21 16:00:00+00:00
[2025-05-22T06:36:05.663+0000] {standard_task_runner.py:72} INFO - Started process 670 to run task
[2025-05-22T06:36:05.666+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_minio_to_spark', 'kafka_producer', 'scheduled__2025-05-21T16:00:00+00:00', '--job-id', '204', '--raw', '--subdir', 'DAGS_FOLDER/testlog_ml.py', '--cfg-path', '/tmp/tmppg3zeka8']
[2025-05-22T06:36:05.667+0000] {standard_task_runner.py:105} INFO - Job 204: Subtask kafka_producer
[2025-05-22T06:36:05.691+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_minio_to_spark.kafka_producer scheduled__2025-05-21T16:00:00+00:00 [running]> on host d1f65538eb5f
[2025-05-22T06:36:05.725+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_minio_to_spark' AIRFLOW_CTX_TASK_ID='kafka_producer' AIRFLOW_CTX_EXECUTION_DATE='2025-05-21T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-21T16:00:00+00:00'
[2025-05-22T06:36:05.726+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-22T06:36:05.734+0000] {conn.py:380} INFO - <BrokerConnection node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: connecting to host.docker.internal:9092 [('192.168.65.254', 9092) IPv4]
[2025-05-22T06:36:05.734+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2025-05-22T06:36:05.736+0000] {conn.py:410} INFO - <BrokerConnection node_id=bootstrap-0 host=host.docker.internal:9092 <connecting> [IPv4 ('192.168.65.254', 9092)]>: Connection complete.
[2025-05-22T06:36:05.847+0000] {conn.py:1267} INFO - Broker version identified as 2.5.0
[2025-05-22T06:36:05.847+0000] {conn.py:1268} INFO - Set configuration api_version=(2, 5, 0) to skip auto check_version requests on startup
[2025-05-22T06:36:05.850+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 68, in kafka_producer
    producer.send('userlog', key=user_id.encode('utf-8'),value=event)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 578, in send
    key_bytes = self._serialize(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/opt/airflow/dags/testlog_ml.py", line 59, in <lambda>
    key_serializer=lambda k: k.encode('utf-8'),
AttributeError: 'bytes' object has no attribute 'encode'
[2025-05-22T06:36:05.855+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=kafka_to_minio_to_spark, task_id=kafka_producer, run_id=scheduled__2025-05-21T16:00:00+00:00, execution_date=20250521T160000, start_date=20250522T063605, end_date=20250522T063605
[2025-05-22T06:36:05.860+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-22T06:36:05.861+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 204 for task kafka_producer ('bytes' object has no attribute 'encode'; 670)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/testlog_ml.py", line 68, in kafka_producer
    producer.send('userlog', key=user_id.encode('utf-8'),value=event)
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 578, in send
    key_bytes = self._serialize(
  File "/home/airflow/.local/lib/python3.10/site-packages/kafka/producer/kafka.py", line 714, in _serialize
    return f(data)
  File "/opt/airflow/dags/testlog_ml.py", line 59, in <lambda>
    key_serializer=lambda k: k.encode('utf-8'),
AttributeError: 'bytes' object has no attribute 'encode'
[2025-05-22T06:36:05.890+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-22T06:36:05.901+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T06:36:05.902+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
