[2025-05-19T07:23:16.508+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-19T07:23:16.579+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_parquet.csv_to_parquet scheduled__2025-05-19T07:05:00+00:00 [queued]>
[2025-05-19T07:23:16.583+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_parquet.csv_to_parquet scheduled__2025-05-19T07:05:00+00:00 [queued]>
[2025-05-19T07:23:16.583+0000] {taskinstance.py:2865} INFO - Starting attempt 8 of 8
[2025-05-19T07:23:16.587+0000] {taskinstance.py:2888} INFO - Executing <Task(SSHOperator): csv_to_parquet> on 2025-05-19 07:05:00+00:00
[2025-05-19T07:23:16.590+0000] {standard_task_runner.py:72} INFO - Started process 1071 to run task
[2025-05-19T07:23:16.592+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'csv_to_parquet', 'csv_to_parquet', 'scheduled__2025-05-19T07:05:00+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/log_to_csv.py', '--cfg-path', '/tmp/tmpq6j844a9']
[2025-05-19T07:23:16.592+0000] {standard_task_runner.py:105} INFO - Job 39: Subtask csv_to_parquet
[2025-05-19T07:23:16.609+0000] {task_command.py:467} INFO - Running <TaskInstance: csv_to_parquet.csv_to_parquet scheduled__2025-05-19T07:05:00+00:00 [running]> on host 8b6a4ce3396b
[2025-05-19T07:23:16.634+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='csv_to_parquet' AIRFLOW_CTX_TASK_ID='csv_to_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T07:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-19T07:05:00+00:00'
[2025-05-19T07:23:16.634+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-19T07:23:16.638+0000] {ssh.py:124} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2025-05-19T07:23:16.641+0000] {base.py:84} INFO - Retrieving connection 'local_ssh'
[2025-05-19T07:23:16.642+0000] {ssh.py:309} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2025-05-19T07:23:16.686+0000] {transport.py:1923} INFO - Connected (version 2.0, client OpenSSH_9.8)
[2025-05-19T07:23:16.886+0000] {transport.py:1923} INFO - Authentication (password) successful!
[2025-05-19T07:23:16.888+0000] {ssh.py:493} INFO - Running command: 
            export JAVA_HOME=/Library/Java/JavaVirtualMachines/openjdk-17.jdk/Contents/Home &&             export PATH=$JAVA_HOME/bin:$PATH &&             /Users/jeongmieun/app/spark/bin/spark-submit /Users/jeongmieun/test/docker_***/dags/spark_to_parquet.py
            
[2025-05-19T07:23:17.384+0000] {ssh.py:544} WARNING - 25/05/19 16:23:17 WARN Utils: Your hostname, jeongmieun-ui-MacBookAir.local resolves to a loopback address: 127.0.0.1; using 172.16.24.224 instead (on interface en0)
[2025-05-19T07:23:17.386+0000] {ssh.py:544} WARNING - 25/05/19 16:23:17 WARN Utils: Set SPARK_LOCAL_IP if you need to bind to another address
[2025-05-19T07:23:17.806+0000] {ssh.py:539} INFO - Traceback (most recent call last):
[2025-05-19T07:23:17.806+0000] {ssh.py:539} INFO -   File "/Users/jeongmieun/test/docker_***/dags/spark_to_parquet.py", line 7, in <module>
[2025-05-19T07:23:17.806+0000] {ssh.py:539} INFO -     from minio import Minio
[2025-05-19T07:23:17.807+0000] {ssh.py:539} INFO - ModuleNotFoundError: No module named 'minio'
[2025-05-19T07:23:17.820+0000] {ssh.py:544} WARNING - 25/05/19 16:23:17 INFO ShutdownHookManager: Shutdown hook called
[2025-05-19T07:23:17.820+0000] {ssh.py:544} WARNING - 25/05/19 16:23:17 INFO ShutdownHookManager: Deleting directory /private/var/folders/3z/zfz369yn0ts877jx33hl_46r0000gn/T/spark-718a89ec-75ab-4d08-a925-854504840298
[2025-05-19T07:23:17.856+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 178, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 172, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2025-05-19T07:23:17.859+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=csv_to_parquet, task_id=csv_to_parquet, run_id=scheduled__2025-05-19T07:05:00+00:00, execution_date=20250519T070500, start_date=20250519T072316, end_date=20250519T072317
[2025-05-19T07:23:17.865+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-19T07:23:17.865+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 39 for task csv_to_parquet (SSH operator error: exit status = 1; 1071)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 190, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 178, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/ssh/operators/ssh.py", line 172, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 1
[2025-05-19T07:23:17.892+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-19T07:23:17.902+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T07:23:17.902+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
